services:
  database: 
    image: postgres:${POSTGRES_VERSION:-17}
    container_name: reposting_bot_database_${APP_VERSION:-latest}
    volumes:
      - ../docker-data/postgres:/var/lib/postgresql/data
    env_file:
      - database.env
  bot:
    container_name: reposting_bot_${APP_VERSION:-latest}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - APP_VERSION=${APP_VERSION:-latest}
        - BUILD_DATE=${BUILD_DATE:-unknown}
        - GIT_COMMIT=${GIT_COMMIT:-unknown}
    image: reposting_bot:${APP_VERSION:-latest}
    volumes:
      - ../dev.db:/app/dev.db
      - ../bot.log:/app/bot.log
    env_file:
      - ../.env
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - APP_VERSION=${APP_VERSION:-latest}
      - BUILD_DATE=${BUILD_DATE:-unknown}
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      