"""Add Review containing several articles

Revision ID: 06cf1a862366
Revises: 92211f022421
Create Date: 2025-09-09 17:52:15.932528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cf1a862366'
down_revision: Union[str, Sequence[str], None] = '92211f022421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_articles_review_id', 'reviews', ['review_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_review_id', type_='foreignkey')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###
